"--auto" flag to automatically guess OS' path and the --latest chat!
somogyijanos/cursor-chat-export pull request #1
Opened 2024-07-23 21:02 UTC by danimesq

2024-07-24 05:18 UTC, somogyijanos commented on chat.py
> +        base_path = home / ".config" / "Cursor" / "User" / "workspaceStorage"
This is duplicate like this, let's refactor getting the default path into a separate function which can be then used by both `get_auto_db_path` and `get_auto_base_path`.

2024-07-24 05:19 UTC, somogyijanos requested changes
I don't know what these `.gitmeta` files are but please remove them.

2024-07-24 23:54 UTC, danimesq commented
@somogyijanos done

2024-07-25 09:13 UTC, somogyijanos commented on chat.py
>  def get_auto_base_path() -> str:
I know you've actually just done, what I've written before literally, but now I see `get_auto_base_path` is just not needed anymore, let's just directly use `get_cursor_workspace_path` in `discover`.

2024-07-25 09:14 UTC, somogyijanos requested changes
👆🏻

2024-07-25 15:42 UTC, danimesq commented
Tested on my end, all working fine using `--auto` both on `--latest` and on `--recent`.

2024-07-26 06:45 UTC, somogyijanos commented on README.md
> +- `--latest`: Exports only the most recent tab from the latest workspace.
Ah yeah, I like these two separate features!

2024-07-26 07:11 UTC, somogyijanos commented on chat.py
Hm, getting confused a bit. I really like the option to export all  or the latest tab from the most recent workspace. I also like automatically detecting the path to the vscdb file. But I think we don't need both separately, I mean detecting the path automatically makes only sense if we don't want to input any path, this also means we're expecting to export from the most recent workspace (either the latest tab or all of them). So my suggestion to make it less confusing:

`discover`:
- make the `db_path` argument optional, if not provided, it will be determined automatically

`export`:
- make the `db_path` argument optional, if not provided, it will be determined automatically to be the latest workspace
- `--latest-tab`/ `--all-tabs` boolean flag pair for specifying that only the latest tab gets exported or all tabs (default)
- usage
  - export all tabs from a specific workspace: `export /path/to/db.vscdb`
  - export latest tab from a specific workspace: `export --latest-tab /path/to/db.vscdb`
  - export all tabs from latest workspace: `export`
  - export latest tab from latest workspace: `export --latest-tab`

2024-07-26 07:12 UTC, somogyijanos requested changes
👆🏻

2024-07-26 14:27 UTC, danimesq commented
@somogyijanos, committing here, on an older branch, will break my other branches.
Moving to a single PR with all of the features of the recent branches: https://github.com/somogyijanos/cursor-chat-export/pull/3.
If there's anything you want me to remove/change/add, #3 is the PR now.

2024-07-26 14:27 UTC, closed without merging