PR Pack
somogyijanos/cursor-chat-export pull request #3
Opened 2024-07-26 14:25 UTC by danimesq

This PR is a joint of all of my recent branches with the following features:
- "--auto" flag to automatically guess OS' path and the --latest chat (+ the --recent workspace)!
- Show the AI model used in a message
- Install system-wide
- Don't create empty `images/` folder when there were no images

2024-07-26 14:36 UTC, danimesq commented
@somogyijanos 

> Hm, getting confused a bit. I really like the option to export all or the latest tab from the most recent workspace. I also like automatically detecting the path to the vscdb file. But I think we don't need both separately, I mean detecting the path automatically makes only sense if we don't want to input any path, this also means we're expecting to export from the most recent workspace (either the latest tab or all of them). So my suggestion to make it less confusing:
> 
> discover:
> 
>     make the db_path argument optional, if not provided, it will be determined automatically
> 
> export:
> 
>     make the db_path argument optional, if not provided, it will be determined automatically to be the latest workspace
>     --latest-tab/ --all-tabs boolean flag pair for specifying that only the latest tab gets exported or all tabs (default)
>     usage
>         export all tabs from a specific workspace: export /path/to/db.vscdb
>         export latest tab from a specific workspace: export --latest-tab /path/to/db.vscdb
>         export all tabs from latest workspace: export
>         export latest tab from latest workspace: export --latest-tab

Did you also mean to remove the `--auto` flag?

2024-07-26 15:28 UTC, somogyijanos commented
Yep, I'd cover this functionality by making the path argument optional for both commands, so if it's not provided it means it's determined automatically. For `discover` this means the base path, for `export` the latest workspace folder.

2024-07-26 16:15 UTC, danimesq commented
@somogyijanos are the latest commit covering all?

2024-07-31 12:09 UTC, somogyijanos commented on install.sh
@danimesq I'm not sure yet I want an installation like this, please put it at least into another PR until I think about how the installation would be best. Thanks!

2024-07-31 12:11 UTC, somogyijanos commented on install.sh
Please adjust the README.md accordingly.

2024-07-31 12:11 UTC, somogyijanos requested changes
👆🏻

Everything else looks super good to me!

2024-08-01 15:00 UTC, danimesq commented
@somogyijanos done in: https://github.com/somogyijanos/cursor-chat-export/pull/3/commits/1969b9990e45e25371dd7fde9ec5f2e54788660d

2024-08-02 07:42 UTC, somogyijanos commented on README.md
> +    git clone https://github.com/somogyijanos/python3 chat.py.git
I think here you replaced `cursor-chat-export` by accident ;)

2024-08-02 07:44 UTC, somogyijanos commented on README.md
> +If you used the automated installation script, you can use the `python3 chat.py` command instead of `./chat.py` in the following examples. This is useful for quickly exporting the chat on your curren
This part isn't updated.

2024-08-02 07:45 UTC, somogyijanos commented on README.md
> +python3 chat.py export --output-dir output "/Users/myuser/Library/Application Support/Cursor/User/workspaceStorage/b989572f2e2186b48b808da2da437416/state.vscdb"
Here's a lot of things doubled, please update.

2024-08-02 07:46 UTC, somogyijanos requested changes
Some changes needed in `README.md`.

2024-08-02 18:20 UTC, danimesq commented
@somogyijanos hopefully fixed now.

2024-08-07 10:33 UTC, somogyijanos commented
I spent some time with these new features and did some refact, see #5. Thanks @danimesq for your contrib!

2024-08-07 10:34 UTC, merged